-- CreateTable
CREATE TABLE "Campeonato" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nombre" TEXT NOT NULL,
    "categorias" INTEGER NOT NULL,
    "creacion" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
